
- name: check to see if cert dirs exist
  stat: path="{{ logstash_ssl_dir }}"
  register: ssl_cert_dir_check

- name: Create ssl cert dir {{ logstash_ssl_dir }}
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory
    mode: 0775
    recurse: yes
  when: ssl_cert_dir_check.stat.exists == False
  become: yes

- name: check to see if cert file exist
  stat: path="{{ logstash_ssl_dir }}/{{ logstash_ssl_certificate_file }}"
  register: ssl_cert_check

- name: check to see if cert key file exist
  stat: path="{{ logstash_ssl_dir }}/{{ logstash_ssl_key_file }}"
  register: ssl_cert_key_check

- name: create ssl cert and private key
  shell: |
    openssl req -x509 -batch -nodes -days 3650 -newkey rsa:2048 -keyout {{ logstash_ssl_dir }}/{{ logstash_ssl_key_file }} -out {{ logstash_ssl_dir }}/{{ logstash_ssl_certificate_file }} -subj '/{{ logstash_ssl_domain }}/'
  when: (ssl_cert_check.stat.exists == False or ssl_cert_key_check.stat.exists == False)
  become: yes
