
- debug:
    msg: "debug value === {{ logstash_install_method }}"

- include_tasks: create_cert.yml

- include: "Install_{{ logstash_install_method | lower }}_{{ansible_os_family}}.yml"

- name: Config Logstash service 
  service:
    name: logstash
    enabled: yes
    state: started
  become: yes